file(GLOB SVGS svg/*.svg)
file(GLOB CONFIGS config/*.in)

set(SVGDIR ${CMAKE_SOURCE_DIR}/svg)
set(CONFIGDIR ${CMAKE_SOURCE_DIR}/config)
set(MAKE_CONFIG_SCRIPT ${CMAKE_SOURCE_DIR}/make_config)
set(MAKE_CONFIG ${MAKE_CONFIG_SCRIPT})
set(MAKE_SVG_SCRIPT ${CMAKE_SOURCE_DIR}/make_svg)
set(MAKE_SVG ${MAKE_SVG_SCRIPT})
